services:
#    france_tv_api.example:
#        class: FranceTV\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
